# Generated by Django 4.0.3 on 2022-03-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listings_description_comments_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='listingImage',
            field=models.FileField(default='ImageFiles/Default_File.jpg', upload_to='ImageFiles/'),
        ),
    ]
