# Generated by Django 4.0.3 on 2022-03-19 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listings_listingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2022, 3, 19, 23, 24, 19, 646089)),
        ),
    ]
