# Generated by Django 4.0.3 on 2022-03-19 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listings_dateposted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2022, 3, 19, 23, 31, 27, 921337)),
        ),
        migrations.AlterField(
            model_name='listings',
            name='listingImage',
            field=models.CharField(max_length=4096),
        ),
    ]
