# Generated by Django 4.0.3 on 2022-03-19 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_comments_commenton_alter_listings_dateposted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bidOn',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.listings'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listings',
            name='datePosted',
            field=models.DateField(default=datetime.datetime(2022, 3, 19, 23, 55, 0, 589873)),
        ),
    ]
